### PR TITLE
feat: optional peer dependencies with dynamic import 

### PR DESCRIPTION
**Pull request by chnejohnson**
## Description
- To provide opt-in wallet provider modules to install
- #101 

## Info
- This PR would bump vue-dapp version to 0.7.0
- It can be tested via install `vue-dapp@0.7.0-beta.10` or using this [template](https://github.com/chnejohnson/vue3-dapp-starter/blob/feat/peers/package.json)
- [x] Gnosis Safe feature has not yet been tested
- In this new version, the package consumer should install wallet provider packages by hand
    - Support WalletConnect
    ```bash
    yarn add @walletconnect/web3-provider
    ```
    - Support Coinbase Wallet
    ```bash
    yarn add @coinbase/wallet-sdk
    ```
    - Support Gnosis Safe
    ```bash
    yarn add @gnosis.pm/safe-apps-provider @gnosis.pm/safe-apps-sdk
    ```
 - This version can drastically reduce the bundle size (https://bundlephobia.com/package/vue-dapp@0.7.0-beta.10)
    截圖 2022-12-16 下午5 00 54
    截圖 2022-12-16 下午5 01 19

## Reference
- https://juejin.cn/post/7115061363965165576
- https://github.com/vitejs/vite/issues/6007
- https://stackoverflow.com/questions/72862593/how-to-publish-a-js-package-that-gracefully-fails-if-an-optional-peer-dependency
- https://github.com/wagmi-dev/references/blob/44b0c4c91147c2aae9689560ddc5f9acbecdfa29/packages/connectors/src/coinbaseWallet.ts#L122

### CODE REVIEW

**Comment by chnejohnson** [comment]
Gnosis Safe App always complains about this error to me...
@re2005 Do you have any experience in testing the dapp on Gnosis Safe?

截圖 2022-12-19 下午12 00 38拷貝

I used this manifest https://github.com/chnejohnson/vue-dapp/blob/feat/peers/demo/public/manifest.json and test it both with vite dev server, preview build files, or [netlify.app](https://deploy-preview-103--vue-dapp.netlify.app/) but neither of them succeed.

**Comment by re2005** [comment]
Hi @chnejohnson I've just tested and for me works fine, when running locally and also when loading the demo from `https://vue-dapp.netlify.app/`

vue-dapp

Maybe some cache or some localStorage old data on your side ?

Cheers

**Comment by re2005** [comment]
Only problem for me is after adding the `Dapp` seems that the Connector is not added to the DEMO.


Screenshot 2022-12-19 at 07 42 53

**Comment by re2005** [comment]
I can confirm that on the `main` branch just by adding the `manifest.json`

/src/public/manifest.json

```json
{
    "short_name": "vue-dapp",
    "name": "Vue Dapp",
    "description": "Vue Dapp safe app test",
    "icons": [
        {
            "src": "favicon.ico",
            "sizes": "32x32",
            "type": "image/x-icon"
        }
    ],
    "start_url": ".",
    "display": "standalone",
    "theme_color": "#ff007a",
    "background_color": "#fff"
}
```
It is working fine.

Screenshot 2022-12-19 at 07 56 41

**Comment by chnejohnson** [comment]
Oh, I see, thank you! I used Safe's new App [app.safe.global](https://app.safe.global/) not carefully. 🤦

Will handle the connector not found error later. 

@re2005 Just in case, have you succeeded to run your app on the rebranded Safe App? If it's easy to test it in the new one I can update it in this commit, or maybe we can wait and open another issue to support the rebranded Safe App.

**Comment by re2005** [comment]
Hey @chnejohnson yes, just checked and my `app` runs nicely (https://app.gelato.network/)

Screenshot 2022-12-19 at 09 22 09

**Comment by chnejohnson** [comment]
Wait...I have no idea why I can't load the demo https://vue-dapp.netlify.app/ even in the old Safe App. It seems that manifest.js is blocked by CORS...but why...

截圖 2022-12-19 下午9 17 15

(btw, I really like the UI Design of your app, so beautiful!

**Comment by re2005** [comment]
Sir! You are right, I totally forgot that for other purposes I've a `CORS` Chrome plugin, that bypass the CORS restrictions, on my browser.

Is that a restriction from `Netlify` itself ? You may can migrate the DEMO to `Vercel` probably won't have this issue.

**Comment by chnejohnson** [comment]
@re2005 Got it. Not sure what's the restriction from Netlify but I will try to deploy it to Vercel, thanks

**Pull request merged**
