### PR TITLE
Call hook

### PR DESCRIPTION
**Pull request by kjpou1**
Initial commit for support of `useCall` and `useCalls` hooks.

The two hooks use contract method calls under the hood if `Multicall2` is not supported for the network.
If `Multicall2` is supported by the network as defined by [multicall2-contract-addresses](https://github.com/makerdao/multicall#multicall2-contract-addresses%60) then the calls will automatically be batch and fed to the `Multicall2` contract.

This makes it easier to call contract methods without having to worry if multi call contracts will be used or not.

If this is something that is wanted in the library I will finish up the documentation.

### CODE REVIEW

**Comment by chnejohnson** [comment]
OMG, this is good I guess, not much to look over here yet, having the documentation will be very helpful!

**Comment by kjpou1** [comment]
> OMG, this is good I guess, not much to look over here yet, having the documentation will be very helpful!

Take a look at the implementations used by the [demo preview](https://deploy-preview-40--vue-dapp.netlify.app/)

I will update the docs in a little bit.

**Comment by kjpou1** [comment]
Are the docs updated by hand or generated from some source

**Comment by chnejohnson** [comment]
> Are the docs updated by hand or generated from some source
The docs are updated by hand at the moment. 

Cool, it's awesome. Because there are lots of functionalities, I will publish a beta version (v0.4.9-beta.0) in the beginning.

And thanks for your contributions!

**Pull request merged**
